name: wop3desenvolvimento_app
description: WOP3 DESENVOLVIMENTO HUMANO.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  characters: ^1.0.0
  firebase: ^7.3.0
  data: ^0.2.0
  cloud_firestore_web: ^0.1.1+2
  cloud_firestore: ^0.13.4+2
  firebase_core: ^0.4.4+3
  firebase_dart: ^0.7.15+4
  firebase_auth: ^0.16.0
  html: ^0.14.0+3
  flutter_html: ^0.11.1
  url_launcher: ^5.4.2
  flutter_time_picker_spinner: ^1.0.6
  direct_select_flutter: ^1.0.5
  charts_flutter: ^0.9.0
  font_awesome_flutter: ^8.7.0
  date_format: ^1.0.8
  flutter_emoji: ^2.2.1+1
  pdf: ^1.8.1
  flutter_radar_chart: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/fundo.png
    - images/fb-icon.png
    - images/reset-password-icon.png
    - images/perc/p07_01.jpg
    - images/perc/p07_02.jpg
    - images/perc/p07_03.jpg
    - images/perc/p07_04.jpg
    - images/perc/p07_05.jpg
    - images/perc/p07_06.jpg
    - images/perc/p07_07.jpg
    - images/perc/p07_08.jpg
    - images/perc/p07_09.jpg
    - images/perc/p07_10.jpg
    - images/perc/p07_11.jpg
    - images/perc/p07_12.jpg
    - images/perc/p07_13.jpg
    - images/perc/p07_14.jpg
    - images/perc/p07_15.jpg
    - images/perc/p07_16.jpg
    - images/perc/p07_17.jpg
    - images/perc/p07_18.jpg
    - images/perc/p07_19.jpg
    - images/perc/p07_20.jpg
    - images/perc/p07_21.jpg
    - images/perc/p07_22.jpg
    - images/perc/p07_23.jpg
    - images/perc/p07_24.jpg
    - images/perc/p07_25.jpg
    - images/perc/p07_26.jpg
    - images/perc/p07_27.jpg
    - images/perc/p08_01.jpg
    - images/perc/p08_02.jpg
    - images/perc/p08_03.jpg
    - images/perc/p08_04.jpg
    - images/perc/p08_05.jpg
    - images/perc/p08_06.jpg
    - images/perc/p08_07.jpg
    - images/perc/p08_08.jpg
    - images/perc/p08_09.jpg
    - images/perc/p08_10.jpg
    - images/perc/p08_11.jpg
    - images/perc/p08_12.jpg
    - images/perc/p08_13.jpg
    - images/perc/p08_14.jpg
    - images/perc/p08_15.jpg
    - images/perc/p08_16.jpg
    - images/perc/p08_17.jpg
    - images/perc/p08_18.jpg
    - images/perc/p08_19.jpg
    - images/perc/p08_20.jpg
    - images/perc/p08_21.jpg
    - images/perc/p08_22.jpg
    - images/perc/p08_23.jpg
    - images/perc/p08_24.jpg
    - images/perc/p08_25.jpg
    - images/perc/p08_26.jpg
    - images/t01.gif
    - images/t02.gif
    - images/t03.gif
    - images/t04.gif
    - images/t05.gif
    - images/t06.gif
    - images/t07.gif
    - images/t08.gif
    - images/t09.gif
    - images/t10.gif
    - images/t11.gif
    - images/t12.gif
    - images/t13.gif
    - images/t14.gif
    - images/t15.gif
    - images/t16.gif
    - images/t17.gif
    - images/t18.gif
    - images/t19.gif
    - images/t20.gif
    - images/t21.gif
    - images/t22.gif
    - images/t23.gif
    - images/t24.gif
    - images/t25.gif
    - images/t26.gif
    - images/t27.gif
    - images/t28.gif
    - images/t29.gif
    - images/t30.gif
    - images/t31.gif
    - images/t32.gif
    - images/t33.gif
    - images/t34.gif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
